### ISSUE TITLE
TypeScript error (TS1345)

### ISSUE THREAD

**Issue by roj1512** [grammyjs/rateLimiter#1]
There is an error when using `rateLimiter` the latest TypeScript with Deno (in which the library is checked).

The full error:

```text
error: TS1345 [ERROR]: An expression of type 'void' cannot be tested for truthiness.
    if (!keyCheck) {
         ~~~~~~~~
    at https://deno.land/x/grammy_ratelimiter@v1.1.4/rateLimiter.ts:39:10
```

Example reproduction code:

```ts
import "https://deno.land/x/grammy_ratelimiter@v1.1.4/rateLimiter.ts";
```

**Comment by KnorpelSenf** [comment]
https://github.com/grammyjs/rateLimiter/blob/4cbfc15ec71d814969b919f73b9ebbd876af95f8/src/typesAndDefaults.ts#L55 should return a string, it's simply a wrong annotation. Which Deno versions work for you, and when does it break?

**Comment by roj1512** [comment]
I haven’t tried other Deno versions.

```text
roj@roj:~ 
 $ deno --version
deno 1.20.6 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```
